name: myrealty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  dio: ^4.0.6
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  cached_network_svg_image: ^0.0.2
  intl: ^0.18.0
  shimmer: ^2.0.0
  path_provider: ^2.0.14
  http: ^0.13.5
  image_picker: ^0.8.7+4
  device_info_plus: ^8.2.2
  share_plus: ^6.3.4
  carousel_slider: ^4.2.1
  uuid: ^3.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/